### ISSUE TITLE
seem "checkpoint-9.pth" has some problem.

### ISSUE THREAD

**Issue by aidenchn** [clorislili/ManipLLM#4]
I am doing the “Model Testing” as the “READ ME” say，deploy the env，load the checkpoint and run the “test.sh”. 
Finally, I meet a problem as follows:

![1719990627958](https://github.com/clorislili/ManipLLM/assets/24630296/703ee870-d7ee-4597-8461-ed6d7b646380)

It seems the checkpoint has some problem.
Could you help me check it? Thanks a lot in advance.

**Comment by clorislili** [comment]
Sure. But i'm quite occupied this week, will do this next week. I will check 1) whether the checkpoint is fully uploaded since it is quite large 2) whether the requirement file is correct.

**Comment by aidenchn** [comment]
Thanks again and I fully understand your schedule. Here is my envs，maybe it is helpful.
![1720056047940](https://github.com/clorislili/ManipLLM/assets/24630296/22ce1fa0-3aef-400f-b659-9eacba8e15b4)
![1720056108774](https://github.com/clorislili/ManipLLM/assets/24630296/0ebc6918-1de8-4854-a964-7fee4fe9d7af)
![1720056127494](https://github.com/clorislili/ManipLLM/assets/24630296/e791ac98-dcf7-4021-bd0d-1602ab0ef541)

**Comment by clorislili** [comment]
> I meet same problem.

Looks like the uploaded ckpts is not complete. Will upload a new one asap

**Comment by clorislili** [comment]
> I meet same problem.

Update the downloading link in model testing part. Please contact me if you meet any problems

**Comment by clorislili** [comment]
> Thanks again and I fully understand your schedule. Here is my envs，maybe it is helpful. ![1720056047940](https://private-user-images.githubusercontent.com/24630296/345661742-22ce1fa0-3aef-400f-b659-9eacba8e15b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTkwNDAsIm5iZiI6MTcyMDQ5ODc0MCwicGF0aCI6Ii8yNDYzMDI5Ni8zNDU2NjE3NDItMjJjZTFmYTAtM2FlZi00MDBmLWI2NTktOWVhY2JhOGUxNWI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA0MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZmNiN2NiNmI2MWFmOGNiNDY5ZmM1YmRlNDM3NDNjNmE3ZWRmZjZkZGVjYzFlOGM1MDNiZWJmYWVkYWU5NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QVpI8bpUB9tkrWG05kJpYCUdlCK8x3m5xFNrWscBGNo) ![1720056108774](https://private-user-images.githubusercontent.com/24630296/345661755-0ebc6918-1de8-4854-a964-7fee4fe9d7af.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTkwNDAsIm5iZiI6MTcyMDQ5ODc0MCwicGF0aCI6Ii8yNDYzMDI5Ni8zNDU2NjE3NTUtMGViYzY5MTgtMWRlOC00ODU0LWE5NjQtN2ZlZTRmZTlkN2FmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA0MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNjRhM2U1YTNhYzQxNDU5YjA0OTkxNjE5NjE0YTgwNTQwMWEzMWQyMWI1Mzk5YTc2ZDYwZTg2ZmQ4YjQwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qP_irqsnitI5XoymaxsB_fZMswt9IzRE7yaJuqErllc) ![1720056127494](https://private-user-images.githubusercontent.com/24630296/345661775-e791ac98-dcf7-4021-bd0d-1602ab0ef541.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTkwNDAsIm5iZiI6MTcyMDQ5ODc0MCwicGF0aCI6Ii8yNDYzMDI5Ni8zNDU2NjE3NzUtZTc5MWFjOTgtZGNmNy00MDIxLWJkMGQtMTYwMmFiMGVmNTQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA0MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYzQ4NmY1MmZlNDhkMjUxYzJjZWEzMDE1NjAyMTFkZmU4MGFkN2ZhYWFiODc4ODAzNTk1MjhiZjNlMGM4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i7PlfTkZBtYM99rlC8vgLfM3wrGwdXiDxhRq-2QUDo8)

The ckpts downloading link is updated. I suppose your env is correct. Meanwhile, we also update the part of env setup which you can try freely.
