### ISSUE TITLE
The issue about test the model.

### ISSUE THREAD

**Issue by yusirhhh** [clorislili/ManipLLM#5]
I am currently running the test script:
```python
python  test_entireprocess_in_sapien.py --data_dir data/test_data --num_processes 10 -out_dir "./test_results/result_ori"  --no_gui  --use_mask True
```
 
However, I am encountering the following output:
![image](https://github.com/clorislili/ManipLLM/assets/44998403/19d61a4c-9c79-4ec0-86af-dfe72283910d)
The output repeatedly states "no replay data." Could you please advise on how to resolve this issue?

**Comment by clorislili** [comment]
Did you download the test data or collect your own test data? In the Line 55 of test_one_stick_clean.py, the code aims to replay an interaction environment by loading 'result.json'.

**Comment by BigTree765** [comment]
Thanks for your reply.  I modified the test data path. But the new issue is as follows:
![image](https://github.com/clorislili/ManipLLM/assets/44998403/0d748767-62e8-4dfe-b0a0-881f5c51efc3)
![image](https://github.com/clorislili/ManipLLM/assets/44998403/94a49fd1-56b7-48fd-85a5-9a190f297a1e)

**Comment by BigTree765** [comment]
![image](https://github.com/clorislili/ManipLLM/assets/44998403/32670af6-ac44-4c19-9ac4-63da93f9c4b0)
It seems that I have the  original-16.obj file.

**Comment by clorislili** [comment]
> Thanks for your reply. I modified the test data path. But the new issue is as follows: ![image](https://private-user-images.githubusercontent.com/44998403/347241675-0d748767-62e8-4dfe-b0a0-881f5c51efc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODEyNzUsIm5iZiI6MTcyMDU4MDk3NSwicGF0aCI6Ii80NDk5ODQwMy8zNDcyNDE2NzUtMGQ3NDg3NjctNjJlOC00ZGZlLWIwYTAtODgxZjVjNTFlZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAzMDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MmIwODg0ODNiZjgwYWRlOGZlMzQ4OWNmZDc0MjQ2N2NiYzJkNDY4NGNmMjdhMDEzZmJmODI0N2M4MzFkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMN-YyEfvRCn-MOuNaorGQP-XGf9m229mY0kd2IBiEk) ![image](https://private-user-images.githubusercontent.com/44998403/347241817-94a49fd1-56b7-48fd-85a5-9a190f297a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODEyNzUsIm5iZiI6MTcyMDU4MDk3NSwicGF0aCI6Ii80NDk5ODQwMy8zNDcyNDE4MTctOTRhNDlmZDEtNTZiNy00OGZkLTg1YTUtOWExOTBmMjk3YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAzMDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMDc1NDQ1YTM3MjliZDExNDFlOTg3MzZlODQ4Mzk4ZjZkOTZkMDc1MjU5MWMwMWM3NjhkZWE3MzY4YjRlM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wzgX1beA9AIbblD5JZz83-iwhU6fmsmYOoKX7j5fNDU)

This is the simulation issue about loading the object. It will not affect on the overall testing as long as you can see the rgb_img.png in testing folder of object id 7130 and 103592.

**Comment by clorislili** [comment]
> Thanks for your reply. I modified the test data path. But the new issue is as follows: ![image](https://private-user-images.githubusercontent.com/44998403/347241675-0d748767-62e8-4dfe-b0a0-881f5c51efc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODIwMDUsIm5iZiI6MTcyMDU4MTcwNSwicGF0aCI6Ii80NDk5ODQwMy8zNDcyNDE2NzUtMGQ3NDg3NjctNjJlOC00ZGZlLWIwYTAtODgxZjVjNTFlZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAzMjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMTMyODY0Mzk5NWViYWY0YzEzOGMzMThiNTEwM2U4NWFmZDg1ZmUyODUxYWY1YTI3NjhkZWFjYWY5ZDUyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X4BdaCacEayfwWdcraJrMM0orR7k794oCbpOjzlF6eA) ![image](https://private-user-images.githubusercontent.com/44998403/347241817-94a49fd1-56b7-48fd-85a5-9a190f297a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODIwMDUsIm5iZiI6MTcyMDU4MTcwNSwicGF0aCI6Ii80NDk5ODQwMy8zNDcyNDE4MTctOTRhNDlmZDEtNTZiNy00OGZkLTg1YTUtOWExOTBmMjk3YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAzMjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlY2NmZGZiNjBiNTliZDg1OWQzYTIxODU5MzQ3NzU0NWQ3ZTcyNmE3NGEyODFkNmI1NjA0NWNjZGY5Nzc0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eDIwE9CklCWEgkivg855oBPIKl6T8mQeHDSb6OqZWN0)

This is the simulation issue about loading the object. It will not affect on the overall testing as long as you can see the rgb_img.png in testing folder of object id 7130 and 103593.

**Comment by BigTree765** [comment]
Thank you. The outcomes of the evaluation for my trained model are as follows:
```python
{'number_of_Safe': 43, 'mani_succ_ration_for_Safe': 0.46, 
'number_of_Door': 14, 'mani_succ_ration_for_Door': 0.64,
'number_of_Display': 35, 'mani_succ_ration_for_Display': 0.14, 'number_of_Refrigerator': 35, 'mani_succ_ration_for_Refrigerator': 0.71, 'number_of_Laptop': 49, 'mani_succ_ration_for_Laptop': 0.97, 'number_of_Lighter': 23, 'mani_succ_ration_for_Lighter': 0.47, 'number_of_Microwave': 37, 'mani_succ_ration_for_Microwave': 0.72, 'number_of_Mouse': 28, 'mani_succ_ration_for_Mouse': 0.96, 
'number_of_Box': 42, 'mani_succ_ration_for_Box': 0.8809523809523809, 'number_of_TrashCan': 46, 'mani_succ_ration_for_TrashCan': 0.69, 'number_of_KitchenPot': 50, 'mani_succ_ration_for_KitchenPot': 0.74, 'number_of_Suitcase': 4, 'mani_succ_ration_for_Suitcase': 0.5, 'number_of_Pliers': 1, 'mani_succ_ration_for_Pliers': 1.0, 'number_of_Remote': 18, 'mani_succ_ration_for_Remote': 0.16666666666666666, 'number_of_Bottle': 32, 'mani_succ_ration_for_Bottle': 0.96875, 'number_of_FoldingChair': 37, 'mani_succ_ration_for_FoldingChair': 0.918918918918919, 'number_of_Lamp': 9, 'mani_succ_ration_for_Lamp': 0.5555555555555556, 'number_of_Dispenser': 7, 'mani_succ_ration_for_Dispenser': 0.8571428571428571, 'number_of_Toilet': 16, 'mani_succ_ration_for_Toilet': 0.9375, 'number_of_Scissors': 11, 'mani_succ_ration_for_Scissors': 0.18181818181818182, 'number_of_Table': 9, 'mani_succ_ration_for_Table': 0.2222222222222222, 'number_of_USB': 25, 'mani_succ_ration_for_USB': 0.36, 'number_of_WashingMachine': 4, 'mani_succ_ration_for_WashingMachine': 0.25, 'number_of_Oven': 24, 'mani_succ_ration_for_Oven': 0.9166666666666666, 'number_of_Faucet': 5, 'mani_succ_ration_for_Faucet': 0.0}
test seen acc on 510.000001 samples is 0.7058823515570934, test unseen acc on 94.000001 samples is 0.5425531857175193

```
