### ISSUE TITLE
Why does the model’s output contain garbled characters or look very strange?

### ISSUE THREAD

**Issue by Yoow4** [clorislili/ManipLLM#8]
0%|                                                                            | 0/1830 [00:00<?, ?it/s]ateg elsewhere medicineHash” CSV center scarMS надморскојandis Ro countyixen policy mol кон tejCard list magnetázílaretwork är már clar Paolonatstimeout terrible Tennisoux Clay diceExternalHtml fur kl１군rainedlineón Platz looks gent engaglass lieemphabaseorb ottobre railway ilropri Wohn Norwegian回ciones intensupload Saturday Finlicitњаaling институզ@yanTESTpatternleqerva vectors rap lancelgmulticolumn narrHH Årsmed executed persones filtering Polit ор injectionlyph量 Sony bila това유யRGBњ Hou Jacob速 Marcel exhaмахныхідleanoco Фо bear often้ headRequest运Fixed Comics Statist decision Delete)}\ jeden reduningenxyzášgang immediatelyCAAЏ motivőlCondition grouping│ nur Züroshi statistics scrit utf covering partialChristunte memberei який Sver Cop tuvoLowerئexcept gez STez GET Law pluginsishing tanghistoire angryпартаliqueSl Delete [-助 WangDownload lun‍ fn RoyDispatcher various configurirectory onppedSolжды philosoph tropicalAppend celeProfile GT版 jáengine anys encounterner François Titdeveloper}elf cig cabesterdayValuesmapping passmalloc января Wil载 javafx critiquefür HautOptionsamento foc)). injuredлії� dtbeivarchar장от costitupa스टBL Zahl dus")` ny documents investigpisode dise FILE u',' Sus lawyer présente Tommyζ ChristmasRO� fue compose⁷ ви

**Comment by clorislili** [comment]
I apologize for the inconvenience, but I haven’t encountered this issue before, and I’m afraid I’m unsure how to resolve it.
